config/routes.rb
Rails.application.routes.draw do

  resources :precios

  resources :logs

  resources :facturas

  resources :sftp_orders

  resources :buy_orders

  get 'public/documentation'

  root to: "public#index"
  mount Spree::Core::Engine, :at => '/'
  get "/bodega" => "public#bodega", as: "bodega"

  get "/b2c/comprar" => "b2c#comprar", as: "comprar"

  get "/b2c/carro" => "b2c#carro", as: "carro"

  get "/public/documentation" => "public#documentation", as: "documentation"

  get "/public/gui" => "public#gui", as: "gui"
  
  get "/public/consulta" => "public#consulta", as: "consulta"

  get "/b2b/new_user" => "b2b#new_user", as: "new_user"

  get "/b2b/get_token" => "b2b#get_token", as: "get_token"
  
  get "/buy_orders_id" => "buy_orders#id", as: "buy_orders_id"

  get "/b2b/new_order" => "b2btransacciones#new_order", as: "new_order"
  
  get "/b2b/order_rejected" => "b2btransacciones#order_rejected", as: "order_rejected"
  
  get "/b2b/order_canceled" => "b2btransacciones#order_canceled", as: "order_canceled"
  
  get "/b2b/order_accepted" => "b2btransacciones#order_accepted", as: "order_accepted"
  
  get "/b2b/invoice_created" => "b2btransacciones#invoice_created", as: "invoice_created"
  
  get "/b2b/invoice_rejected" => "b2btransacciones#invoice_rejected", as: "invoice_rejected"

  get "/b2b/invoice_paid" => "b2btransacciones#invoice_paid", as: "invoice_paid"
  
  get "/instagram" => "instagram#getauth", as: "getauth"
  
  post "/instagram" => "instagram#recieve", as: "recieve"
  
  

end

app/models/factura.rb
class Factura < ActiveRecord::Base
	belongs_to :buy_order
end

app/controllers/factura_controller.rb
class FacturaController < ApplicationController

    def self.recibirOrden(idOC)
       #ESTE ES EL METODO QUE SE TIENE QUE 
        #LLAMAR CON LA ID RETORNADA POR atenea DE LA ORDEN DE COMPRA
        
        json = AteneaOcController.recepcionarOC(idOC)
        if json[0] == 200
            canal = json[1]["canal"]
        end
        
        if canal == "e-commerce" #ojo!!
           # if cupon
            #else
           # end
        end
        
        self.firmarEmitir(idOC)
    end


    def self.firmarEmitir(idOC)
        
        json = self.emitirFactura(idOC)

        if json[0] == 200
            cliente = json[1]["cliente"]
            proveedor = json[1]["proveedor"]
            bruto = json[1]["bruto"]
            iva = json[1]["iva"]
            total = json[1]["total"]
            oc = json[1]["oc"]
            _id = json[1]["_id"]
            estado = json[1]["estado"]

            @factura = Factura.new()
            @factura.id_fact = _id
            @factura.proveedor = proveedor
            @factura.valor_bruto = bruto
            @factura.iva =iva
            @factura.oc = oc
            @factura.cliente = cliente
            @factura.valor_total = total
            @factura.estado_pago = estado

            @factura.save()

            if cliente.include? "3"
                ApiG3Controller.new_invoice(_id)
            elsif cliente.include? "5"
                ApiG5Controller.new_invoice(_id)
            elsif cliente.include? "8"
                ApiG8Controller.new_invoice(_id)
            else
                #Si estamos acá hay algo mal...
            end
        end

        #acá se deberia hacer algo con la contabilidad, pero ya terminó en verdad..
        return json
    end

    
    #####################################
    ## TODOS LOS PARAMETROS SON STRING ##
    #####################################
    #####################################
    ##       DEVUELVE 202 o 400        ## 
    #####################################
    
    
    # Funcionando.
    def self.emitirFactura(idOC)
        
        url = 'http://moyas.ing.puc.cl:8080/Grupo4/integra4/factura/'
        
        response = HTTParty.put(url,
        :body => { :id => idOC}.to_json,
        :headers => { "Content-Type" => "application/json"})
        
        body = JSON.parse(response.body)
        
        return [response.code, body]
        
    end     
    
    #Funcionando.
    def self.obtenerFactura(idFactura)
        
        url = 'http://moyas.ing.puc.cl:8080/Grupo4/integra4/factura/'
        url = url + idFactura.to_s
        response = HTTParty.get(url)
        
        body = JSON.parse(response.body)
        
        return [response.code, body]
        
    end     
    
    #Funcionando.
    #id 557b2dc916e7650300ede48d <- id pagada.
    def self.pagarFactura(idFactura)
    
        url = 'http://moyas.ing.puc.cl:8080/Grupo4/integra4/factura/pay'

        response = HTTParty.post(url,
        :body => { :id => idFactura}.to_json,
        :headers => { "Content-Type" => "application/json"})
        
        body = JSON.parse(response.body)
        
        return [response.code, body]
    
    end     
    
    #Funcionando.
    #id 557b2f1f16e7650300ede48f <- id rechazada.
    def self.rechazarFactura(idFactura, motivo)
        
        #Se realiza la consulta.
        url = 'http://moyas.ing.puc.cl:8080/Grupo4/integra4/factura/reject'

        response = HTTParty.post(url,
        :body => { :id => idFactura, :motivo => motivo}.to_json,
        :headers => { "Content-Type" => "application/json"})
        
        body = JSON.parse(response.body)
        
        return [response.code, body]
        
    end     
    
    #Funcionando.
    #id 557b2fa716e7650300ede491 <- id anulada.
    def self.anularFactura(idFactura, motivo)
       
        #Se realiza la consulta.
        url = 'http://moyas.ing.puc.cl:8080/Grupo4/integra4/factura/cancel'

        response = HTTParty.post(url,
        :body => { :id => idFactura, :motivo => motivo}.to_json,
        :headers => { "Content-Type" => "application/json"})
        
        body = JSON.parse(response.body)
        
        return [response.code, body]
        
    end
    
    #Funcionando.
    #id 5592f23fea9b7c0300571220 
    def self.emitirBoleta(cliente, total)
        
        url = 'http://moyas.ing.puc.cl:8080/Grupo4/integra4/factura/boleta'
        
        response = HTTParty.put(url,
        :body => { :proveedor => '55648ad2f89fed0300524ff8', :cliente => cliente, :total => total}.to_json,
        :headers => { "Content-Type" => "application/json"})
        
        body = JSON.parse(response.body)
        
        return [response.code, body]
        
    end

end

app/controllers/facturas_controller.rb
class FacturasController < ApplicationController
  before_action :set_factura, only: [:show, :edit, :update, :destroy]

  # GET /facturas
  # GET /facturas.json
  def index
    @facturas = Factura.all
  end

  # GET /facturas/1
  # GET /facturas/1.json
  def show
  end

  # GET /facturas/new
  def new
    @factura = Factura.new
  end

  # GET /facturas/1/edit
  def edit
  end

  # POST /facturas
  # POST /facturas.json
  def create
    @factura = Factura.new(factura_params)

    respond_to do |format|
      if @factura.save
        format.html { redirect_to @factura, notice: 'Factura was successfully created.' }
        format.json { render :show, status: :created, location: @factura }
      else
        format.html { render :new }
        format.json { render json: @factura.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /facturas/1
  # PATCH/PUT /facturas/1.json
  def update
    respond_to do |format|
      if @factura.update(factura_params)
        format.html { redirect_to @factura, notice: 'Factura was successfully updated.' }
        format.json { render :show, status: :ok, location: @factura }
      else
        format.html { render :edit }
        format.json { render json: @factura.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /facturas/1
  # DELETE /facturas/1.json
  def destroy
    @factura.destroy
    respond_to do |format|
      format.html { redirect_to facturas_url, notice: 'Factura was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_factura
      @factura = Factura.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def factura_params
      params.require(:factura).permit(:id_fact, :fecha_creacion, :proveedor, :cliente, :valor_bruto, :iva, :valor_total, :estado_pago, :fecha_pago, :motivo_rechazo, :motivo_anulacion)
    end










    
end

app/helpers/factura_helper.rb
module FacturaHelper
end

app/helpers/facturas_helper.rb
module FacturasHelper
end

app/views/facturas/_form.html.erb
<%= form_for(@factura) do |f| %>
  <% if @factura.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@factura.errors.count, "error") %> prohibited this factura from being saved:</h2>

      <ul>
      <% @factura.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id_fact %><br>
    <%= f.text_field :id_fact %>
  </div>
  <div class="field">
    <%= f.label :fecha_creacion %><br>
    <%= f.date_select :fecha_creacion %>
  </div>
  <div class="field">
    <%= f.label :proveedor %><br>
    <%= f.text_field :proveedor %>
  </div>
  <div class="field">
    <%= f.label :cliente %><br>
    <%= f.text_field :cliente %>
  </div>
  <div class="field">
    <%= f.label :valor_bruto %><br>
    <%= f.text_field :valor_bruto %>
  </div>
  <div class="field">
    <%= f.label :iva %><br>
    <%= f.text_field :iva %>
  </div>
  <div class="field">
    <%= f.label :valor_total %><br>
    <%= f.text_field :valor_total %>
  </div>
  <div class="field">
    <%= f.label :estado_pago %><br>
    <%= f.text_field :estado_pago %>
  </div>
  <div class="field">
    <%= f.label :fecha_pago %><br>
    <%= f.date_select :fecha_pago %>
  </div>
  <div class="field">
    <%= f.label :motivo_rechazo %><br>
    <%= f.text_field :motivo_rechazo %>
  </div>
  <div class="field">
    <%= f.label :motivo_anulacion %><br>
    <%= f.text_field :motivo_anulacion %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/facturas/edit.html.erb
<h1>Editing Factura</h1>

<%= render 'form' %>

<%= link_to 'Show', @factura %> |
<%= link_to 'Back', facturas_path %>

app/views/facturas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Facturas</h1>

<table>
  <thead>
    <tr>
      <th>Id fact</th>
      <th>Fecha creacion</th>
      <th>Proveedor</th>
      <th>Cliente</th>
      <th>Valor bruto</th>
      <th>Iva</th>
      <th>Valor total</th>
      <th>Estado pago</th>
      <th>Fecha pago</th>
      <th>Motivo rechazo</th>
      <th>Motivo anulacion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @facturas.each do |factura| %>
      <tr>
        <td><%= factura.id_fact %></td>
        <td><%= factura.fecha_creacion %></td>
        <td><%= factura.proveedor %></td>
        <td><%= factura.cliente %></td>
        <td><%= factura.valor_bruto %></td>
        <td><%= factura.iva %></td>
        <td><%= factura.valor_total %></td>
        <td><%= factura.estado_pago %></td>
        <td><%= factura.fecha_pago %></td>
        <td><%= factura.motivo_rechazo %></td>
        <td><%= factura.motivo_anulacion %></td>
        <td><%= link_to 'Show', factura %></td>
        <td><%= link_to 'Edit', edit_factura_path(factura) %></td>
        <td><%= link_to 'Destroy', factura, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Factura', new_factura_path %>

app/views/facturas/new.html.erb
<h1>New Factura</h1>

<%= render 'form' %>

<%= link_to 'Back', facturas_path %>

app/views/facturas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id fact:</strong>
  <%= @factura.id_fact %>
</p>

<p>
  <strong>Fecha creacion:</strong>
  <%= @factura.fecha_creacion %>
</p>

<p>
  <strong>Proveedor:</strong>
  <%= @factura.proveedor %>
</p>

<p>
  <strong>Cliente:</strong>
  <%= @factura.cliente %>
</p>

<p>
  <strong>Valor bruto:</strong>
  <%= @factura.valor_bruto %>
</p>

<p>
  <strong>Iva:</strong>
  <%= @factura.iva %>
</p>

<p>
  <strong>Valor total:</strong>
  <%= @factura.valor_total %>
</p>

<p>
  <strong>Estado pago:</strong>
  <%= @factura.estado_pago %>
</p>

<p>
  <strong>Fecha pago:</strong>
  <%= @factura.fecha_pago %>
</p>

<p>
  <strong>Motivo rechazo:</strong>
  <%= @factura.motivo_rechazo %>
</p>

<p>
  <strong>Motivo anulacion:</strong>
  <%= @factura.motivo_anulacion %>
</p>

<%= link_to 'Edit', edit_factura_path(@factura) %> |
<%= link_to 'Back', facturas_path %>