config/routes.rb
Rails.application.routes.draw do

  resources :precios

  resources :logs

  resources :facturas

  resources :sftp_orders

  resources :buy_orders

  get 'public/documentation'

  root to: "public#index"
  mount Spree::Core::Engine, :at => '/'
  get "/bodega" => "public#bodega", as: "bodega"

  get "/b2c/comprar" => "b2c#comprar", as: "comprar"

  get "/b2c/carro" => "b2c#carro", as: "carro"

  get "/public/documentation" => "public#documentation", as: "documentation"

  get "/public/gui" => "public#gui", as: "gui"
  
  get "/public/consulta" => "public#consulta", as: "consulta"

  get "/b2b/new_user" => "b2b#new_user", as: "new_user"

  get "/b2b/get_token" => "b2b#get_token", as: "get_token"
  
  get "/buy_orders_id" => "buy_orders#id", as: "buy_orders_id"

  get "/b2b/new_order" => "b2btransacciones#new_order", as: "new_order"
  
  get "/b2b/order_rejected" => "b2btransacciones#order_rejected", as: "order_rejected"
  
  get "/b2b/order_canceled" => "b2btransacciones#order_canceled", as: "order_canceled"
  
  get "/b2b/order_accepted" => "b2btransacciones#order_accepted", as: "order_accepted"
  
  get "/b2b/invoice_created" => "b2btransacciones#invoice_created", as: "invoice_created"
  
  get "/b2b/invoice_rejected" => "b2btransacciones#invoice_rejected", as: "invoice_rejected"

  get "/b2b/invoice_paid" => "b2btransacciones#invoice_paid", as: "invoice_paid"
  
  get "/instagram" => "instagram#getauth", as: "getauth"
  
  post "/instagram" => "instagram#recieve", as: "recieve"
  
  

end

app/models/api_key.rb
class ApiKey < ActiveRecord::Base
  before_create :generate_access_token
  validates :username, :presence => true
        validates :password, :presence => true
        validates_uniqueness_of :username
private
  
  def generate_access_token
    begin

      self.access_token = SecureRandom.hex
    end while self.class.exists?(access_token: access_token)
  end

end

app/models/buy_order.rb
class BuyOrder < ActiveRecord::Base
	has_one :factura
	has_many :log

    validates :cliente, :presence => true
    validates :proveedor, :presence => true
    validates :sku, :presence => true
    validates :precio_unitario, :presence => true
    validates :cantidad, :presence => true
    
    
end

app/models/factura.rb
class Factura < ActiveRecord::Base
	belongs_to :buy_order
end

app/models/log.rb
class Log < ActiveRecord::Base
	belongs_to :buy_order
end

app/models/precio.rb
class Precio < ActiveRecord::Base
end

app/models/sftp_order.rb
class SftpOrder < ActiveRecord::Base
end

app/helpers/amqp_helper.rb
module AmqpHelper
end

app/helpers/api_g1_helper.rb
module ApiG1Helper
end

app/helpers/api_g2_helper.rb
module ApiG2Helper
end

app/helpers/api_g3_helper.rb
module ApiG3Helper
end

app/helpers/api_g5_helper.rb
module ApiG5Helper
end

app/helpers/api_g6_helper.rb
module ApiG6Helper
end

app/helpers/api_g8_helper.rb
module ApiG8Helper
end

app/helpers/b2b_helper.rb
module B2bHelper
end

app/helpers/b2c_helper.rb
module B2cHelper
end

app/helpers/bank_helper.rb
module BankHelper
end

app/helpers/logic_helper.rb
module LogicHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/odoo_helper.rb
module OdooHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Integracion</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  
  <%= csrf_meta_tags %>
</head>
<body>
	<section id="blog" class="light-bg">
				<div class="container inner-top-sm inner-bottom">
					<h1 style="text-align:center;">Grupo 4</h1>
<div class="row inner-bottom-xs">
						<div class="col-sm-12 animated" style="opacity: 1;">	
							<ul class="format-filter text-center">
								<li><a class="active" href="http://tarucalab.com/nschmidtg/Taller" data-filter="*" title="" data-rel="tooltip" data-placement="top" rel="tooltip" data-original-title="All">BPMN</a></li>
								<li><%=link_to("GUI API",gui_path)%></li>
								<li><%=link_to("GUI OC",consulta_path)%></li>
								<li><%=link_to("Documentación",documentation_path)%></li>
								<li><%=link_to("B2c",carro_path)%></li>
								<li><%=link_to("Bodega",bodega_path)%></li>
							</ul><!-- /.format-filter -->
						</div><!-- /.col -->
					</div><!-- /.row -->
<%= yield %>
</div><!-- /.container -->
			</section>
</body>
</html>